module.exports =
{ accounts:
  [ { account_id: 'JpGN5ELowxTd1LaxGx8JH4pLpjxbV6FpJb3Ve',
      balances: { available: 100, current: 110, limit: null },
      mask: '0000',
      name: 'Plaid Checking',
      official_name: 'Plaid Gold Standard 0% Interest Checking',
      subtype: 'checking',
      type: 'depository' },
    { account_id: '5lwMgopqnbswXzjlqlJGskGQGdxlaMtzdxlq8',
      balances: { available: 200, current: 210, limit: null },
      mask: '1111',
      name: 'Plaid Saving',
      official_name: 'Plaid Silver Standard 0.1% Interest Saving',
      subtype: 'savings',
      type: 'depository' },
    { account_id: 'lkXQKZE8mDc4R6ZmXmx1I3MmM5pKxDi17LQDg',
      balances: { available: null, current: 1000, limit: null },
      mask: '2222',
      name: 'Plaid CD',
      official_name: 'Plaid Bronze Standard 0.2% Interest CD',
      subtype: 'cd',
      type: 'depository' },
    { account_id: 'kleQqyEgMDs9LBjAyAGas5EAEGxoJ1Hrpxny7',
      balances: { available: null, current: 410, limit: 2000 },
      mask: '3333',
      name: 'Plaid Credit Card',
      official_name: 'Plaid Diamond 12.5% APR Interest Credit Card',
      subtype: 'credit card',
      type: 'credit' }
  ],
 item:
  { available_products: [ 'balance' ],
    billed_products: [ 'auth', 'transactions' ],
    error: null,
    institution_id: 'ins_1',
    item_id: '7KJ5EpqrRbtlR31BrB5JUlBgxLKWrqsgzQXgj',
    webhook: '' },
 numbers:
  [ { account: '1111222233330000',
      account_id: 'JpGN5ELowxTd1LaxGx8JH4pLpjxbV6FpJb3Ve',
      routing: '011401533',
      wire_routing: '021000021' },
    { account: '1111222233331111',
      account_id: '5lwMgopqnbswXzjlqlJGskGQGdxlaMtzdxlq8',
      routing: '011401533',
      wire_routing: '021000021' } ],
 request_id: 'Bw7Bw',
  status_code: 200 }