module.exports=
[
  '1st Advantage Federal Credit Union',
  '1st Mariner Bank',
  'A+ Federal Credit Union',
  'Allegiance Credit Union',
  'Ally Bank',
  'Amegy Bank',
  'American Chartered Bank',
  'BancFirst',
  'Bankers Trust',
  'Bank Midwest',
  'Bank Mutual',
  'Bank of Albuquerque',
  'Bank of Arizona',
  'Bank of Arkansas',
  'Bank of Hawaii',
  'Bank of Kansas City',
  'Bank of Oklahoma',
  'Bank of Texas',
  'Bank of the Ozarks',
  'BankUnited',
  'Banner Bank',
  'BECU',
  'Berkshire Bank',
  'Cadence Bank',
  'Cambridge Savings Bank',
  'Capital Bank',
  'Capital City Bank',
  'Capital Federal ',
  'Capital One 360',
  'Cathay Bank',
  'CDC Federal Credit Union',
  'Charles Schwab Bank',
  'City Bank Texas',
  'City National Bank',
  'Colorado State Bank and Trust',
  'Columbia Bank',
  'Community Banks of Colorado',
  'Community Trust Bank',
  'Cornerstone Community FCU',
  'Delta Community Credit Union',
  'Digital Credit Union (DCU)',
  'Dime Community Bank',
  'Dollar Bank',
  'Eastern Bank',
  'ELGA Credit Union',
  'Ent Federal Credit Union',
  'FirstBank',
  'First Community Credit Union',
  'First Financial Bank',
  'First Hawaiian Bank',
  'First Interstate Bank',
  'First Merchants Bank',
  'First National Bank of Omaha',
  'Flushing Bank',
  'FNB Bank, N.A.',
  'FSG Bank',
  'Fulton Bank of NJ',
  'Glacier Bank',
  'Great Southern Bank',
  'GTE Federal Credit Union',
  'Hancock Bank',
  'Iberiabank',
  'Investors Bank',
  'KimCentral Credit Union',
  'Lafayette Ambassador Bank',
  'Lake City Bank',
  'Liberty Bank',
  'MainSource Bank',
  'Metairie Bank ',
  'Middlesex Savings Bank',
  'MidFirst Bank',
  'Morrill & Janes Bank ',
  'National Bank of Arizona',
  'Neighbors Federal Credit Union',
  'Nevada State Bank',
  'OneWest Bank',
  'Park Community Credit Union',
  'Pinnacle Financial Partners',
  'Power Financial Credit Union',
  'Provident Bank',
  'Redwood Credit Union',
  'Renasant Bank',
  'Republic Bank ',
  'Ridgewood Savings Bank',
  'Rockland Trust ',
  'Sandy Spring Bank',
  'SchoolsFirst Federal Credit Union',
  'SECU (Maryland)',
  'Simmons First National Bank',
  'Spencer Savings Bank',
  'Summit Credit Union',
  'Swineford National Bank',
  'Texas Bay Area Credit Union',
  'Texas First Bank',
  'Texas Trust Credit Union',
  'The Columbia Bank',
  'The PrivateBank ',
  'Third Federal Savings & Loan ',
  'Tobyhanna FCU',
  'Towne Bank',
  'Tri City National Bank',
  'Trustco Bank',
  'Union Bank ',
  'Union Bank & Trust',
  'Univest Bank and Trust Co.',
  'USAA Federal Savings Bank',
  'Vectra Bank ',
  'Wayne Bank',
  'Westbury Bank',
  'Workers Credit Union',
  'WSFS Bank',
  'Xceed Financial Credit Union'
]